FROM node:20.18.3-alpine3.21 AS dev-deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

FROM node:20.18.3-alpine3.21 AS dev-setup
WORKDIR /app
COPY --from=dev-deps /app/node_modules ./node_modules
COPY . .
RUN npm install -g tsx
CMD ["tsx", "watch", "src/index.ts"]