
FROM node:20.18.3 as dev-deps 
WORKDIR /app
COPY package.json package.json
RUN npm ci

FROM node:20.18.3 as builder
WORKDIR /app
COPY --from=dev-deps /app/node_modules ./node_modules
COPY . .
RUN npm build

FROM node:20.18.3 as prod-deps
WORKDIR /app
COPY package.json package.json
RUN npm install --production


FROM node:20.18.3 as prod
WORKDIR /app
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

CMD [ "node","dist/main.js"]